[workspace]

members = [
    "webhook",
    "ratelimiter",
    "gateway"
]

[package]
name = "nova"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "nova"
path = "src/main.rs"

[dependencies]
libc = "0.2.101"

[package.metadata.raze]
workspace_path = "//cargo"
genmode = "Remote"
default_gen_buildrs = true
package_aliases_dir = "cargo"
experimental_api = true

[package.metadata.raze.crates.cpufeatures.'*']
skipped_deps = ["libc-0.2.101"]
additional_deps = ["@raze__libc__0_2_101//:libc"]

[package.metadata.raze.crates.ring.'*']
compile_data_attr = "glob([\"*/**\"])"
skipped_deps = ["once_cell-1.8.0"]
additional_deps = ["@raze__once_cell__1_8_0//:once_cell"]

[package.metadata.raze.crates.flate2.'*']
compile_data_attr = "glob([\"*/**\"])"
skipped_deps = ["miniz_oxide-0.4.4"]
additional_deps = ["@raze__miniz_oxide__0_4_4//:miniz_oxide"]


[package.metadata.raze.crates.webpki.'*']
compile_data_attr = "glob([\"*/**\"])"

[package.metadata.raze.crates.libsodium-sys.'*']
buildrs_additional_environment_variables = { PATH = "/usr/sbin:/usr/bin:/sbin:/bin", "NUM_JOBS" = "2" }
compile_data_attr = "glob([\"*/**\"])"
gen_buildrs = false
additional_build_file = ["bazel/patch/libsodium_buildrs.rs"]