[workspace]
members = [
    "exes/cache/",
    "exes/gateway/",
    "exes/rest/",
    "exes/webhook/",
    "exes/ratelimit/",
    "exes/all",

    "libs/proto/",
    "libs/shared/",
    "libs/leash/"
]