version: "3.3"
services:
  nats:
      image: 'nats'
      expose:
        - "4222"
      ports:
        - "8222:8222"
        - "4222:4222"
      hostname: nats-server
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000