[package]
name = "rest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../../libs/shared" }
proto = { path = "../../libs/proto" }
leash = { path = "../../libs/leash" }

hyper= "0.14"
http = "0.2.8"

tokio = { version = "1", features = ["rt"] }
serde = { version = "1.0.8", features = ["derive"] }

hyper-tls = "0.5.0"

# todo(MatthieuCoder): Move to the real twilight when patch is merged
twilight-http-ratelimiting = { git = "https://github.com/MatthieuCoder/twilight.git" }

tracing = "0.1.37"
anyhow = "1.0.68"
hashring = "0.3.0"
tonic = "0.8.3"
tokio-stream = "0.1.11"
dns-lookup = "1.0.8"
opentelemetry = "0.18.0"
opentelemetry-http = "0.7.0"
tracing-opentelemetry = "0.18.0"