monitoring:
  enabled: true
  address: 0.0.0.0
  port: 8001


webhook:
  server:
    address: 0.0.0.0
    port: 8000
  discord:
    client_id: 738817757650485300
    public_key: "2dc5873bb9e603dbf70e6abc217768b9d7dfacef9e74ddaefcca6a9aed41f30d"

