debug: true
server:
  address: "0.0.0.0"
  port: 8000
discord:
  # Theses credentials are public anyways
  client_id: 738817757650485300
  public_key: "475bed67e20fb1e2d9b9007607f08d7b25b5a0aa936ef2d4ddaf7d592c993860"

gateway:
  relaying:
    relay_instances: 0
  clustering:
    cluster_size: 1 # The total number of clusters
    cluster_id: 0 # Current cluster id
    shard_count: 1 # 10 shards by cluster
  discord:
    token: "token"
    large_threshold: 100
    intents: 16384

webhook:
  server:
    address: 0.0.0.0
    port: 8000
  discord:
    client_id: 738817757650485300
    public_key: "475bed67e20fb1e2d9b9007607f08d7b25b5a0aa936ef2d4ddaf7d592c993860"
