version: "3.3"

services:
  nats:
    image: "nats"
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    hostname: nats
    networks:
      - internal

networks:
  internal: {}