monitoring:
  enabled: false
gateway:
  relaying:
    relay_instances: 0
  clustering:
    cluster_size: 1 # The total number of clusters
    cluster_id: 0 # Current cluster id
    shard_count: 1 # 10 shards by cluster
  discord:
    token: "token"
    large_threshold: 100
    intents: 16384